// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiCalls.Data;

#nullable disable

namespace WebApiCalls.Data.Migrations
{
    [DbContext(typeof(WebApiCallsDbContext))]
    partial class WebApiCallsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiCalls.Data.Call", b =>
                {
                    b.Property<int>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CallId"));

                    b.Property<int>("FromId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp");

                    b.Property<int>("ToId")
                        .HasColumnType("integer");

                    b.HasKey("CallId");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("WebApiCalls.Data.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Company")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("WebApiCalls.Data.ContactSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<DateTime?>("TimeClosed")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("TimeLastRequest")
                        .HasColumnType("timestamp");

                    b.HasKey("SessionId");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactSessions");
                });

            modelBuilder.Entity("WebApiCalls.Data.Call", b =>
                {
                    b.HasOne("WebApiCalls.Data.Contact", "FromContacts")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiCalls.Data.Contact", "ToContacts")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromContacts");

                    b.Navigation("ToContacts");
                });

            modelBuilder.Entity("WebApiCalls.Data.ContactSession", b =>
                {
                    b.HasOne("WebApiCalls.Data.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });
#pragma warning restore 612, 618
        }
    }
}
